//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_TERM_KEY
    {
        public decimal APP_TYPE { get; set; }
        public string MERCHANT_ID { get; set; }
        public string TERMINAL_ID { get; set; }
        public string MASTER_KEY { get; set; }
        public string MAC_KEY { get; set; }
        public string PIN_KEY { get; set; }
        public string TERMVERSION { get; set; }
        public string CAPKVERSION { get; set; }
        public string PARAVERSION { get; set; }
        public string CARDTABLEVERSION { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
