//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITMAP_CONTROL
    {
        public decimal RECNO { get; set; }
        public string MSG_TYPE { get; set; }
        public string COND_CODE { get; set; }
        public string FUNC_CODE { get; set; }
        public string PROC_CODE { get; set; }
        public string REQ_MIN_BITMAP { get; set; }
        public string REQ_MAX_BITMAP { get; set; }
        public string RES_MIN_BITMAP { get; set; }
        public string RES_MAX_BITMAP { get; set; }
        public string VERIFIED { get; set; }
        public Nullable<decimal> SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
    }
}
