//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARDS
    {
        public string BANK_NAME { get; set; }
        public string BANK_ID { get; set; }
        public string CARD_NAME { get; set; }
        public string CARD_ID { get; set; }
        public decimal CARD_NO_LEN { get; set; }
        public decimal CARD_SITE2 { get; set; }
        public Nullable<decimal> EXP_SITE2 { get; set; }
        public Nullable<decimal> PAN_SITE3 { get; set; }
        public Nullable<decimal> CARD_SITE3 { get; set; }
        public Nullable<decimal> EXP_SITE3 { get; set; }
        public string CARD_TYPE { get; set; }
        public Nullable<decimal> CARD_LEVEL { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
