//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASH_MACHINE_PARAM_TMP
    {
        public decimal REC_NO { get; set; }
        public string PARAM_CATALOG { get; set; }
        public string PARAM_NAME { get; set; }
        public string PARAM_VALUE { get; set; }
        public Nullable<decimal> ERP_VENDOR_ID { get; set; }
        public string VERIFIED { get; set; }
        public string UPDATE_DATE { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
    }
}
