//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataOnlineEntities : DbContext
    {
        public DataOnlineEntities()
            : base("name=DataOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<APP_DEF> APP_DEF { get; set; }
        public DbSet<APP_DEF_TMP> APP_DEF_TMP { get; set; }
        public DbSet<APP_MENU> APP_MENU { get; set; }
        public DbSet<APP_MENU_TMP> APP_MENU_TMP { get; set; }
        public DbSet<APP_TERM_KEY> APP_TERM_KEY { get; set; }
        public DbSet<APP_TERM_KEY_TMP> APP_TERM_KEY_TMP { get; set; }
        public DbSet<AREA_POS_KEY> AREA_POS_KEY { get; set; }
        public DbSet<ARTCONF> ARTCONF { get; set; }
        public DbSet<BITMAP_CONTROL> BITMAP_CONTROL { get; set; }
        public DbSet<BITMAP_CONTROL_TMP> BITMAP_CONTROL_TMP { get; set; }
        public DbSet<CARDS> CARDS { get; set; }
        public DbSet<CARDS_TMP> CARDS_TMP { get; set; }
        public DbSet<CASH_MACHINE_FILE> CASH_MACHINE_FILE { get; set; }
        public DbSet<CASH_MACHINE_FILE_TMP> CASH_MACHINE_FILE_TMP { get; set; }
        public DbSet<CASH_MACHINE_PARAM> CASH_MACHINE_PARAM { get; set; }
        public DbSet<CASH_MACHINE_PARAM_TMP> CASH_MACHINE_PARAM_TMP { get; set; }
        public DbSet<CASHIERBILLAD> CASHIERBILLAD { get; set; }
        public DbSet<CASHIERBILLAD_TMP> CASHIERBILLAD_TMP { get; set; }
        public DbSet<COMMANDS> COMMANDS { get; set; }
        public DbSet<COMMANDS_TMP> COMMANDS_TMP { get; set; }
        public DbSet<DEPT> DEPT { get; set; }
        public DbSet<DEPT_MATCH_MENU> DEPT_MATCH_MENU { get; set; }
        public DbSet<DEPT_TMP> DEPT_TMP { get; set; }
        public DbSet<DISP_INFO> DISP_INFO { get; set; }
        public DbSet<DISP_INFO_TMP> DISP_INFO_TMP { get; set; }
        public DbSet<DYNAMIC_DETAIL> DYNAMIC_DETAIL { get; set; }
        public DbSet<DYNAMIC_DETAIL_TMP> DYNAMIC_DETAIL_TMP { get; set; }
        public DbSet<DYNAMIC_ITEM> DYNAMIC_ITEM { get; set; }
        public DbSet<DYNAMIC_ITEM_TMP> DYNAMIC_ITEM_TMP { get; set; }
        public DbSet<DYNAMIC_MENU> DYNAMIC_MENU { get; set; }
        public DbSet<DYNAMIC_MENU_TMP> DYNAMIC_MENU_TMP { get; set; }
        public DbSet<DYNAMIC_VALID> DYNAMIC_VALID { get; set; }
        public DbSet<DYNAMIC_VALID_TMP> DYNAMIC_VALID_TMP { get; set; }
        public DbSet<ERP_IN_PARAM_TEMPLATE> ERP_IN_PARAM_TEMPLATE { get; set; }
        public DbSet<ERP_IN_PARAM_TEMPLATE_TMP> ERP_IN_PARAM_TEMPLATE_TMP { get; set; }
        public DbSet<ERP_OUT_PARAM_TEMPLATE> ERP_OUT_PARAM_TEMPLATE { get; set; }
        public DbSet<ERP_OUT_PARAM_TEMPLATE_TMP> ERP_OUT_PARAM_TEMPLATE_TMP { get; set; }
        public DbSet<ERP_PARAM_MAP_DETAIL> ERP_PARAM_MAP_DETAIL { get; set; }
        public DbSet<ERP_PARAM_MAP_DETAIL_TMP> ERP_PARAM_MAP_DETAIL_TMP { get; set; }
        public DbSet<ERP_PARAM_MAPPING> ERP_PARAM_MAPPING { get; set; }
        public DbSet<ERP_PARAM_MAPPING_TMP> ERP_PARAM_MAPPING_TMP { get; set; }
        public DbSet<ERP_VENDOR> ERP_VENDOR { get; set; }
        public DbSet<ERP_VENDOR_TMP> ERP_VENDOR_TMP { get; set; }
        public DbSet<ERROR_CODE> ERROR_CODE { get; set; }
        public DbSet<ERROR_CODE_TMP> ERROR_CODE_TMP { get; set; }
        public DbSet<ERROR_GROUP> ERROR_GROUP { get; set; }
        public DbSet<ERROR_GROUP_MAPPING> ERROR_GROUP_MAPPING { get; set; }
        public DbSet<ERROR_GROUP_MAPPING_TMP> ERROR_GROUP_MAPPING_TMP { get; set; }
        public DbSet<ERROR_GROUP_TMP> ERROR_GROUP_TMP { get; set; }
        public DbSet<ERROR_INFO> ERROR_INFO { get; set; }
        public DbSet<ERROR_INFO_TMP> ERROR_INFO_TMP { get; set; }
        public DbSet<FIELD_MESSAGE> FIELD_MESSAGE { get; set; }
        public DbSet<FIELD_MESSAGE_TMP> FIELD_MESSAGE_TMP { get; set; }
        public DbSet<FILES_MGR> FILES_MGR { get; set; }
        public DbSet<FIRST_PAGE> FIRST_PAGE { get; set; }
        public DbSet<FIRST_PAGE_TMP> FIRST_PAGE_TMP { get; set; }
        public DbSet<FUNCTION_INFO> FUNCTION_INFO { get; set; }
        public DbSet<FUNCTION_INFO_TMP> FUNCTION_INFO_TMP { get; set; }
        public DbSet<H_VOIDLS> H_VOIDLS { get; set; }
        public DbSet<HISTORY_LS> HISTORY_LS { get; set; }
        public DbSet<HSM_AAA> HSM_AAA { get; set; }
        public DbSet<HSM_TMK> HSM_TMK { get; set; }
        public DbSet<MENU_FUNCINFO_MAP> MENU_FUNCINFO_MAP { get; set; }
        public DbSet<MENU_FUNCINFO_MAP_TMP> MENU_FUNCINFO_MAP_TMP { get; set; }
        public DbSet<MENU_OPERINFO_MAP> MENU_OPERINFO_MAP { get; set; }
        public DbSet<MENU_OPERINFO_MAP_TMP> MENU_OPERINFO_MAP_TMP { get; set; }
        public DbSet<MENU_PRINTINFO_MAP> MENU_PRINTINFO_MAP { get; set; }
        public DbSet<MENU_PRINTINFO_MAP_TMP> MENU_PRINTINFO_MAP_TMP { get; set; }
        public DbSet<MENU_TRANS_MAP> MENU_TRANS_MAP { get; set; }
        public DbSet<OPERATION_INFO> OPERATION_INFO { get; set; }
        public DbSet<OPERATION_INFO_R> OPERATION_INFO_R { get; set; }
        public DbSet<OPERATION_INFO_TMP> OPERATION_INFO_TMP { get; set; }
        public DbSet<OPERATION_TEMP> OPERATION_TEMP { get; set; }
        public DbSet<OPERATION_TEMP_TMP> OPERATION_TEMP_TMP { get; set; }
        public DbSet<PLATFORM_SETTLE_CFG> PLATFORM_SETTLE_CFG { get; set; }
        public DbSet<PLATFORM_SETTLE_CFG_TMP> PLATFORM_SETTLE_CFG_TMP { get; set; }
        public DbSet<POS_KEY> POS_KEY { get; set; }
        public DbSet<POS_KEY_TMP> POS_KEY_TMP { get; set; }
        public DbSet<POS_SETTLE_CFG> POS_SETTLE_CFG { get; set; }
        public DbSet<POS_SETTLE_CFG_MODULE> POS_SETTLE_CFG_MODULE { get; set; }
        public DbSet<POS_SETTLE_CFG_MODULE_TMP> POS_SETTLE_CFG_MODULE_TMP { get; set; }
        public DbSet<POS_SETTLE_CFG_TMP> POS_SETTLE_CFG_TMP { get; set; }
        public DbSet<PRINT_DATA> PRINT_DATA { get; set; }
        public DbSet<PRINT_DATA_TMP> PRINT_DATA_TMP { get; set; }
        public DbSet<PRINT_INFO> PRINT_INFO { get; set; }
        public DbSet<PRINT_INFO_R> PRINT_INFO_R { get; set; }
        public DbSet<PRINT_INFO_TMP> PRINT_INFO_TMP { get; set; }
        public DbSet<PRINT_MODULE> PRINT_MODULE { get; set; }
        public DbSet<PRINT_MODULE_GROUP> PRINT_MODULE_GROUP { get; set; }
        public DbSet<PRINT_MODULE_GROUP_MEMBER> PRINT_MODULE_GROUP_MEMBER { get; set; }
        public DbSet<PRINT_MODULE_GROUP_MEMBER_TMP> PRINT_MODULE_GROUP_MEMBER_TMP { get; set; }
        public DbSet<PRINT_MODULE_GROUP_TMP> PRINT_MODULE_GROUP_TMP { get; set; }
        public DbSet<PRINT_MODULE_TMP> PRINT_MODULE_TMP { get; set; }
        public DbSet<PRT_MDL_GRP_MEMBER_SHOP> PRT_MDL_GRP_MEMBER_SHOP { get; set; }
        public DbSet<PRT_MDL_GRP_MEMBER_SHOP_TMP> PRT_MDL_GRP_MEMBER_SHOP_TMP { get; set; }
        public DbSet<RELATION_UNION> RELATION_UNION { get; set; }
        public DbSet<RELATION_UNION_TMP> RELATION_UNION_TMP { get; set; }
        public DbSet<SHOP> SHOP { get; set; }
        public DbSet<SHOP_CODE> SHOP_CODE { get; set; }
        public DbSet<SHOP_TMP> SHOP_TMP { get; set; }
        public DbSet<SMS_ALERT_CONF> SMS_ALERT_CONF { get; set; }
        public DbSet<STD_FEE_CONF> STD_FEE_CONF { get; set; }
        public DbSet<STD_FEE_CONF_TMP> STD_FEE_CONF_TMP { get; set; }
        public DbSet<SYSTEM_PARAMETER> SYSTEM_PARAMETER { get; set; }
        public DbSet<SYSTEM_PARAMETER_TMP> SYSTEM_PARAMETER_TMP { get; set; }
        public DbSet<T_APPTYPE> T_APPTYPE { get; set; }
        public DbSet<T_APPTYPE_TMP> T_APPTYPE_TMP { get; set; }
        public DbSet<T_BASEARG> T_BASEARG { get; set; }
        public DbSet<T_LOCAL_CARD> T_LOCAL_CARD { get; set; }
        public DbSet<T_LOCAL_CARD_TMP> T_LOCAL_CARD_TMP { get; set; }
        public DbSet<T_OPERTION_LOGINFO> T_OPERTION_LOGINFO { get; set; }
        public DbSet<T_STAT_LINE> T_STAT_LINE { get; set; }
        public DbSet<T_STD_TRANS_CONF> T_STD_TRANS_CONF { get; set; }
        public DbSet<T_STD_TRANS_CONF_TMP> T_STD_TRANS_CONF_TMP { get; set; }
        public DbSet<T_TERM_APP> T_TERM_APP { get; set; }
        public DbSet<T_TERM_APP_TMP> T_TERM_APP_TMP { get; set; }
        public DbSet<T_TERM_CONF> T_TERM_CONF { get; set; }
        public DbSet<T_TERM_CONF_TMP> T_TERM_CONF_TMP { get; set; }
        public DbSet<TBL_DISP_CONTENT> TBL_DISP_CONTENT { get; set; }
        public DbSet<TBL_DISP_CONTENT_TMP> TBL_DISP_CONTENT_TMP { get; set; }
        public DbSet<TBL_DOWLOAD_STATUS> TBL_DOWLOAD_STATUS { get; set; }
        public DbSet<TBL_EXCHANGE> TBL_EXCHANGE { get; set; }
        public DbSet<TBL_EXCHANGE_TMP> TBL_EXCHANGE_TMP { get; set; }
        public DbSet<TBL_FAMILY_TERM> TBL_FAMILY_TERM { get; set; }
        public DbSet<TBL_FAMILY_TERM_TMP> TBL_FAMILY_TERM_TMP { get; set; }
        public DbSet<TBL_GUANZIHAO_LS> TBL_GUANZIHAO_LS { get; set; }
        public DbSet<TBL_MENU_PIC_POSITION> TBL_MENU_PIC_POSITION { get; set; }
        public DbSet<TBL_MENU_PIC_POSITION_TMP> TBL_MENU_PIC_POSITION_TMP { get; set; }
        public DbSet<TBL_OFFLINE_PRINT_MODULE> TBL_OFFLINE_PRINT_MODULE { get; set; }
        public DbSet<TBL_OFFLINE_PRINT_MODULE_TMP> TBL_OFFLINE_PRINT_MODULE_TMP { get; set; }
        public DbSet<TBL_ORGCODE> TBL_ORGCODE { get; set; }
        public DbSet<TBL_PARA_CONTENT> TBL_PARA_CONTENT { get; set; }
        public DbSet<TBL_PARA_CONTENT_TMP> TBL_PARA_CONTENT_TMP { get; set; }
        public DbSet<TBL_PRINT_MODULE> TBL_PRINT_MODULE { get; set; }
        public DbSet<TBL_PRINT_MODULE_TMP> TBL_PRINT_MODULE_TMP { get; set; }
        public DbSet<TBL_PROJAPP_ROUTER> TBL_PROJAPP_ROUTER { get; set; }
        public DbSet<TBL_PROJAPP_ROUTER_TMP> TBL_PROJAPP_ROUTER_TMP { get; set; }
        public DbSet<TBL_QR_CODE_CONFIG> TBL_QR_CODE_CONFIG { get; set; }
        public DbSet<TBL_QR_CODE_CONFIG_GROUP> TBL_QR_CODE_CONFIG_GROUP { get; set; }
        public DbSet<TBL_QR_CODE_CONFIG_GROUP_TMP> TBL_QR_CODE_CONFIG_GROUP_TMP { get; set; }
        public DbSet<TBL_QR_CODE_CONFIG_TMP> TBL_QR_CODE_CONFIG_TMP { get; set; }
        public DbSet<TEMPLATE_DEF> TEMPLATE_DEF { get; set; }
        public DbSet<TERM_ERP_MAPPING> TERM_ERP_MAPPING { get; set; }
        public DbSet<TERM_ERP_MAPPING_TMP> TERM_ERP_MAPPING_TMP { get; set; }
        public DbSet<TERM_ROUTER> TERM_ROUTER { get; set; }
        public DbSet<TERM_ROUTER_TMP> TERM_ROUTER_TMP { get; set; }
        public DbSet<TERMINAL> TERMINAL { get; set; }
        public DbSet<TERMINAL_MAP> TERMINAL_MAP { get; set; }
        public DbSet<TERMINAL_MAP_TMP> TERMINAL_MAP_TMP { get; set; }
        public DbSet<TERMINAL_TMP> TERMINAL_TMP { get; set; }
        public DbSet<TESTONE> TESTONE { get; set; }
        public DbSet<TRANS_AUTO> TRANS_AUTO { get; set; }
        public DbSet<TRANS_AUTO_TMP> TRANS_AUTO_TMP { get; set; }
        public DbSet<TRANS_COMMANDS> TRANS_COMMANDS { get; set; }
        public DbSet<TRANS_COMMANDS_TMP> TRANS_COMMANDS_TMP { get; set; }
        public DbSet<TRANS_DEF> TRANS_DEF { get; set; }
        public DbSet<TRANS_DEF_TMP> TRANS_DEF_TMP { get; set; }
        public DbSet<TRANS_LIMIT> TRANS_LIMIT { get; set; }
        public DbSet<TRANS_SPLIT> TRANS_SPLIT { get; set; }
        public DbSet<TRANS_SPLIT_TMP> TRANS_SPLIT_TMP { get; set; }
        public DbSet<TRANS_TYPE_MAPPING> TRANS_TYPE_MAPPING { get; set; }
        public DbSet<TRANS_TYPE_MAPPING_TMP> TRANS_TYPE_MAPPING_TMP { get; set; }
        public DbSet<UNKNOWN_CARD> UNKNOWN_CARD { get; set; }
        public DbSet<VOID_CONFIG> VOID_CONFIG { get; set; }
        public DbSet<VOID_CONFIG_TMP> VOID_CONFIG_TMP { get; set; }
    }
}
