//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYNAMIC_MENU
    {
        public Nullable<decimal> RECNO { get; set; }
        public string TITLE { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> MENU_NUM { get; set; }
        public string MENU_NAME1 { get; set; }
        public string TRANS_CODE1 { get; set; }
        public string MENU_NAME2 { get; set; }
        public string TRANS_CODE2 { get; set; }
        public string MENU_NAME3 { get; set; }
        public string TRANS_CODE3 { get; set; }
        public string MENU_NAME4 { get; set; }
        public string TRANS_CODE4 { get; set; }
        public string MENU_NAME5 { get; set; }
        public string TRANS_CODE5 { get; set; }
        public string MENU_NAME6 { get; set; }
        public string TRANS_CODE6 { get; set; }
        public string MENU_NAME7 { get; set; }
        public string TRANS_CODE7 { get; set; }
        public string MENU_NAME8 { get; set; }
        public string TRANS_CODE8 { get; set; }
        public string MENU_NAME9 { get; set; }
        public string TRANS_CODE9 { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
