//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ERP_PARAM_MAP_DETAIL
    {
        public decimal REC_NO { get; set; }
        public decimal PARAM_MAPPING_ID { get; set; }
        public string PARAM_IN_OUT_TYPE { get; set; }
        public string PARAM_TYPE { get; set; }
        public string PARAM_DATA_TYPE { get; set; }
        public Nullable<decimal> PARAM_DATA_LEN { get; set; }
        public Nullable<decimal> IN_PARAM_TMPLT_ID { get; set; }
        public Nullable<decimal> OUT_PARAM_TMPLT_ID { get; set; }
        public string PARAM_NULLABLE { get; set; }
        public string PARAM_PREFIX_CHARS { get; set; }
        public string PARAM_SUFFIX_CHARS { get; set; }
        public string IS_SUB_PARAM { get; set; }
        public string UPDATE_DATE { get; set; }
        public Nullable<short> CHECK_CODE { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
    }
}
