//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESICPARAINFO
    {
        public string AID { get; set; }
        public string ASI { get; set; }
        public string APP_VER { get; set; }
        public string TAC_DEF { get; set; }
        public string TAC_OL { get; set; }
        public string TAC_REJECT { get; set; }
        public string LWM { get; set; }
        public string LAND_VAL { get; set; }
        public string MAX_PCT { get; set; }
        public string TARGET_PCT { get; set; }
        public string DDOL_DEF { get; set; }
        public string PIN_ABILITY { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string RSV1 { get; set; }
        public string RSV2 { get; set; }
        public string RSV3 { get; set; }
        public string RSV4 { get; set; }
        public string RSV5 { get; set; }
        public string RSV6 { get; set; }
        public string RSV7 { get; set; }
        public string DEPTNO { get; set; }
    }
}
