//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPKINFO
    {
        public string RID { get; set; }
        public string IDX { get; set; }
        public string EFFC_DATE { get; set; }
        public string HSID { get; set; }
        public string PKID { get; set; }
        public string PK_MOD { get; set; }
        public string PK_EXP { get; set; }
        public string CHECK_VALUE { get; set; }
        public Nullable<decimal> STATUS { get; set; }
        public string RSV1 { get; set; }
        public string RSV2 { get; set; }
        public string RSV3 { get; set; }
        public string DEPTNO { get; set; }
    }
}
