//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_LS
    {
        public string HOST_DATE { get; set; }
        public string HOST_TIME { get; set; }
        public string PAN { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string CARD_TYPE { get; set; }
        public Nullable<decimal> TRANS_TYPE { get; set; }
        public Nullable<decimal> TRACE { get; set; }
        public string RETRIREFNUM { get; set; }
        public string AUTH_CODE { get; set; }
        public string TERMINAL_ID { get; set; }
        public string MERCHANT_ID { get; set; }
        public string ACCOUNT2 { get; set; }
        public Nullable<decimal> ADDI_AMOUNT { get; set; }
        public Nullable<decimal> BATCH_NO { get; set; }
        public string PSAM_NO { get; set; }
        public Nullable<decimal> INVOICE { get; set; }
        public string RETURN_CODE { get; set; }
        public string HOST_RET_CODE { get; set; }
        public string CANCEL_FLAG { get; set; }
        public string RECOVER_FLAG { get; set; }
        public string POS_SETTLE { get; set; }
        public string POS_BATCH { get; set; }
        public string HOST_SETTLE { get; set; }
        public Nullable<decimal> POSP_TRACE { get; set; }
        public string OLDRETRIREFNUM { get; set; }
        public string POS_DATE { get; set; }
        public string POS_TIME { get; set; }
        public string USER_CODE1 { get; set; }
        public string USER_CODE2 { get; set; }
        public string BANK_ID { get; set; }
        public string SETTLE_DATE { get; set; }
        public string OPER_NO { get; set; }
        public string MAC { get; set; }
        public string CASHIER_NO { get; set; }
        public string CASH_MACHINE_NO { get; set; }
        public string TRANS_CODE { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string MEMO { get; set; }
    }
}
