//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_TRANS_MAP
    {
        public decimal APP_TYPE { get; set; }
        public string TRANS_CODE { get; set; }
        public Nullable<decimal> USE_COUNT { get; set; }
    }
}
