//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_PRINTINFO_MAP_TMP
    {
        public decimal APP_TYPE { get; set; }
        public Nullable<decimal> REC_NO { get; set; }
        public decimal UUID { get; set; }
        public string VER { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
    }
}
