//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_KEY_TMP
    {
        public Nullable<decimal> KEY_INDEX { get; set; }
        public string MASTER_KEY { get; set; }
        public string MASTER_KEY_LMK { get; set; }
        public string MASTER_CHK { get; set; }
        public string PIN_KEY { get; set; }
        public string MAC_KEY { get; set; }
        public string MAG_KEY { get; set; }
        public string VERIFIED { get; set; }
        public string DELETE_FLAG { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
