//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP_CODE
    {
        public string SHOP_NO { get; set; }
        public decimal TRANS_TYPE { get; set; }
        public string CARD_TYPE { get; set; }
        public Nullable<decimal> SHOP_TYPE { get; set; }
        public string CODE { get; set; }
        public string DESCRIBE { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
