//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SHOP_TMP
    {
        public string SHOP_NO { get; set; }
        public Nullable<decimal> SHOP_TYPE { get; set; }
        public string SHOP_NAME { get; set; }
        public string ACQ_BANK { get; set; }
        public string CONTACTOR { get; set; }
        public string TELEPHONE { get; set; }
        public string ADDR { get; set; }
        public Nullable<decimal> FEE { get; set; }
        public Nullable<decimal> COLLEC_LIMIT { get; set; }
        public Nullable<decimal> COLLEC_TOTAL { get; set; }
        public Nullable<decimal> OUT_LIMIT { get; set; }
        public Nullable<decimal> OUT_TOTAL { get; set; }
        public Nullable<decimal> OTHER_LIMIT { get; set; }
        public Nullable<decimal> OTHER_TOTAL { get; set; }
        public string FAX_NUM { get; set; }
        public Nullable<decimal> SIGN_FLAG { get; set; }
        public string SIGN_DATE { get; set; }
        public string UNSIGN_DATE { get; set; }
        public string DEPTNO { get; set; }
        public string CARD_KIND { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
