//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class STD_FEE_CONF_TMP
    {
        public string TRANS_CODE { get; set; }
        public decimal BEGIN_AMT { get; set; }
        public Nullable<decimal> BEGIN_OPERCODE { get; set; }
        public decimal END_AMT { get; set; }
        public Nullable<decimal> END_OPERCODE { get; set; }
        public decimal FEE { get; set; }
        public string VERIFIED { get; set; }
    }
}
