//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_PARAMETER_TMP
    {
        public Nullable<decimal> SPECIFICATION { get; set; }
        public Nullable<decimal> CUR_KEY_INDEX { get; set; }
        public Nullable<decimal> BATCH_NO { get; set; }
        public Nullable<decimal> TRACE { get; set; }
        public Nullable<decimal> WITHDRAW_LIMIT { get; set; }
        public Nullable<decimal> WITHDRAW_TOTAL { get; set; }
        public Nullable<decimal> FEE_RATE { get; set; }
        public Nullable<decimal> FEE1 { get; set; }
        public Nullable<decimal> FEE2 { get; set; }
        public string CARD_OUT_KIND { get; set; }
        public string CARD_IN_KIND { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
    }
}
