//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_BASEARG
    {
        public string TYPE { get; set; }
        public decimal BASECODE { get; set; }
        public string NAME { get; set; }
        public string PARENTNAME { get; set; }
        public Nullable<decimal> ORGANIZE_CODE { get; set; }
        public string BASEARG_ID { get; set; }
    }
}
