//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OPERTION_LOGINFO
    {
        public decimal ID { get; set; }
        public string MODULE_NAME { get; set; }
        public string METHOD_DESCRIPTION { get; set; }
        public string KEY_ID { get; set; }
        public string KEY_NAME { get; set; }
        public string USER_NAME { get; set; }
        public string DATETIME { get; set; }
    }
}
