//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_STAT_LINE
    {
        public string MERCHANT_ID { get; set; }
        public string TERMINAL_ID { get; set; }
        public string TRANS_DATE { get; set; }
        public Nullable<decimal> SHOP_TYPE { get; set; }
        public string DEPT_NO_1 { get; set; }
        public string DEPT_NO_2 { get; set; }
        public string DEPT_NO_3 { get; set; }
        public string DEPT_NO_4 { get; set; }
        public Nullable<decimal> DEPT_LEVEL { get; set; }
        public string BIND_CARD_NO { get; set; }
        public Nullable<decimal> PUR_COUNT { get; set; }
        public Nullable<decimal> PUR_AMOUNT { get; set; }
        public Nullable<decimal> PUR_FEE { get; set; }
        public Nullable<decimal> PAY_IN_COUNT { get; set; }
        public Nullable<decimal> PAY_IN_AMOUNT { get; set; }
        public Nullable<decimal> PAY_IN_FEE { get; set; }
        public Nullable<decimal> PAY_OUT_COUNT { get; set; }
        public Nullable<decimal> PAY_OUT_AMOUNT { get; set; }
        public Nullable<decimal> PAY_OUT_FEE { get; set; }
        public Nullable<decimal> TYPE_1_COUNT { get; set; }
        public Nullable<decimal> TYPE_1_AMOUNT { get; set; }
        public Nullable<decimal> TYPE_1_FEE { get; set; }
        public Nullable<decimal> TYPE_2_COUNT { get; set; }
        public Nullable<decimal> TYPE_2_AMOUNT { get; set; }
        public Nullable<decimal> TYPE_2_FEE { get; set; }
        public Nullable<decimal> TYPE_3_COUNT { get; set; }
        public Nullable<decimal> TYPE_3_AMOUNT { get; set; }
        public Nullable<decimal> TYPE_3_FEE { get; set; }
        public string RESERVE_1 { get; set; }
    }
}
