//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TERM_APP
    {
        public decimal APP_TYPE { get; set; }
        public string MCHNT_NO { get; set; }
        public string TERM_NO { get; set; }
        public string DEPT_NO { get; set; }
        public string ACQ_NO { get; set; }
        public decimal MAPP_TYPE { get; set; }
        public string TERM_ID { get; set; }
        public string TERMAPP_ID { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string ORI_TERM_ID { get; set; }
        public string PRONAME { get; set; }
        public string PRODETAIL { get; set; }
    }
}
