//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TERM_CONF_TMP
    {
        public string TRANS_CODE { get; set; }
        public string MERCHANT_ID { get; set; }
        public string TERMINAL_ID { get; set; }
        public Nullable<short> FEETYPE { get; set; }
        public Nullable<short> FEEPERCENT { get; set; }
        public Nullable<decimal> SINGLE_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_AMOUNT { get; set; }
        public Nullable<int> MAX_COUNT { get; set; }
        public string CARD_OUT_KIND { get; set; }
        public string CARD_IN_KIND { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
