//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DISP_CONTENT_TMP
    {
        public decimal DATA_INDEX { get; set; }
        public string LINES { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string VERIFIED { get; set; }
        public decimal TIMEOUT { get; set; }
        public decimal CTRL_BITMAP { get; set; }
        public string REFRESH_MODE { get; set; }
    }
}
