//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_OFFLINE_PRINT_MODULE_TMP
    {
        public Nullable<decimal> MODULE { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> PRINT_NUM { get; set; }
        public Nullable<decimal> EN_PRINT_FLAG { get; set; }
        public string TITLE { get; set; }
        public string TRANS_NAME { get; set; }
        public string PRINT_MASK { get; set; }
        public Nullable<decimal> REMARK_PRINT_FLAG { get; set; }
        public string TAGS { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public Nullable<decimal> SIGN_PRINT_FLAG { get; set; }
        public string OTHER_REMARKS { get; set; }
        public string ENDINGS { get; set; }
    }
}
