//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRINT_MODULE
    {
        public Nullable<decimal> MODULE { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> PRINT_NUM { get; set; }
        public Nullable<decimal> TITLE1 { get; set; }
        public Nullable<decimal> TITLE2 { get; set; }
        public Nullable<decimal> TITLE3 { get; set; }
        public Nullable<decimal> SIGN1 { get; set; }
        public Nullable<decimal> SIGN2 { get; set; }
        public Nullable<decimal> SIGN3 { get; set; }
        public Nullable<decimal> REC_NUM { get; set; }
        public string REC_NO { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string LOGO_FLAG { get; set; }
        public string DEPT_NO { get; set; }
    }
}
