//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_GUANZIHAO_LS
    {
        public string HOST_DATE { get; set; }
        public string HOST_TIME { get; set; }
        public string PSAM_NO { get; set; }
        public string MCHNT_NO { get; set; }
        public string TERM_NO { get; set; }
        public Nullable<decimal> BATCH_NO { get; set; }
        public Nullable<decimal> TRACE { get; set; }
        public string MAC { get; set; }
        public string VOID_FLAG { get; set; }
        public string GUANZIHAO { get; set; }
    }
}
