//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_EX_TERM_EVT_TITLE
    {
        public string PID { get; set; }
        public string TITLE_INFO { get; set; }
        public string MCHNT_NO { get; set; }
        public string TERM_NO { get; set; }
        public string CREATED_AT { get; set; }
        public string UPDATED_AT { get; set; }
    }
}
