//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_FAMILY_TERM
    {
        public string PSAM_NO { get; set; }
        public string PERSON_ID { get; set; }
        public string NAME { get; set; }
        public string BIND_CARDS { get; set; }
        public string FLAG { get; set; }
        public string MODIFY_MONTH { get; set; }
        public string MODIFY_TIMES { get; set; }
        public string PHONE_NUMBER { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string VERIFIED { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
