//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ORGCODE
    {
        public decimal OPER_INDEX { get; set; }
        public string OP_FLAG { get; set; }
        public string CITY_CODE { get; set; }
        public string ORG_CODE { get; set; }
        public string ORG_NAME { get; set; }
        public string RESV1 { get; set; }
        public string RESV2 { get; set; }
        public string PAY_TYPE { get; set; }
        public string UPT_DATE { get; set; }
        public string VERIFIED { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
