//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINAL
    {
        public string SHOP_NO { get; set; }
        public string POS_ID { get; set; }
        public string PSAM_NO { get; set; }
        public string TELEPHONE { get; set; }
        public Nullable<decimal> TERM_MODULE { get; set; }
        public Nullable<decimal> PSAM_MODULE { get; set; }
        public Nullable<decimal> APP_TYPE { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> COLLEC_LIMIT { get; set; }
        public Nullable<decimal> COLLEC_TOTAL { get; set; }
        public Nullable<decimal> OUT_LIMIT { get; set; }
        public Nullable<decimal> OUT_TOTAL { get; set; }
        public Nullable<decimal> OTHER_LIMIT { get; set; }
        public Nullable<decimal> OTHER_TOTAL { get; set; }
        public string POS_TYPE { get; set; }
        public string ADDRESS { get; set; }
        public string PUT_DATE { get; set; }
        public Nullable<decimal> CUR_TRACE { get; set; }
        public string IP { get; set; }
        public string DOWN_MENU { get; set; }
        public string DOWN_TERM { get; set; }
        public string DOWN_PSAM { get; set; }
        public string DOWN_PRINT { get; set; }
        public string DOWN_OPERATE { get; set; }
        public string DOWN_FUNCTION { get; set; }
        public string DOWN_ERROR { get; set; }
        public string DOWN_ALL { get; set; }
        public string DOWN_PAYLIST { get; set; }
        public Nullable<decimal> MENU_RECNO { get; set; }
        public Nullable<decimal> PRINT_RECNO { get; set; }
        public Nullable<decimal> OPERATE_RECNO { get; set; }
        public Nullable<decimal> FUNCTION_RECNO { get; set; }
        public Nullable<decimal> ERROR_RECNO { get; set; }
        public Nullable<decimal> ALL_TRANSTYPE { get; set; }
        public string TERM_BITMAP { get; set; }
        public string PSAM_BITMAP { get; set; }
        public string PRINT_BITMAP { get; set; }
        public string OPERATE_BITMAP { get; set; }
        public string FUNCTION_BITMAP { get; set; }
        public string ERROR_BITMAP { get; set; }
        public Nullable<decimal> MSG_RECNUM { get; set; }
        public string MSG_RECNO { get; set; }
        public Nullable<decimal> FIRST_PAGE { get; set; }
        public Nullable<decimal> T_STATUS { get; set; }
        public Nullable<decimal> CUR_BATCH { get; set; }
        public string TERM_ID { get; set; }
        public string DEVTYPE { get; set; }
        public string VERIFIED { get; set; }
        public string SUBMCHNT_BRIEFNAME { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public decimal KEY_IDX { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string AUTO_MATCH_MENU_FLAG { get; set; }
        public string STYLUS_PRINTER_FLAG { get; set; }
        public string NAME_FLAG { get; set; }
        public decimal CASHIERBILLAD_RECNO { get; set; }
        public Nullable<decimal> QR_GROUP { get; set; }
        public string TMIS_PRINTER_FLAG { get; set; }
    }
}
