//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMINAL_MAP_TMP
    {
        public string MCHNT_NO { get; set; }
        public string TERM_NO { get; set; }
        public string DEPT_NO { get; set; }
        public string TGT_SHOP_NO { get; set; }
        public string TGT_TERM_NO { get; set; }
        public string TGT_SHOP_NAME { get; set; }
        public string VERIFIED { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
