//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_APPTERMKEY
    {
        public string APPTYPE { get; set; }
        public string TERMINALID { get; set; }
        public string MASTERKEY { get; set; }
        public string MACKEY { get; set; }
        public string PINKEY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
    }
}
