//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TV_BINDCARD
    {
        public string TERMINALID { get; set; }
        public string BANKCARDNO { get; set; }
        public string USERCODE { get; set; }
        public string USERNAME { get; set; }
        public string IDCARD { get; set; }
        public string PHONENO { get; set; }
        public string BANKNAME { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
    }
}
