//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNKNOWN_CARD
    {
        public string TRACK2 { get; set; }
        public string TRACK3 { get; set; }
        public string S_DATE { get; set; }
        public string FLAG { get; set; }
    }
}
