//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataOnlineEntity2 : DbContext
    {
        public DataOnlineEntity2()
            : base("name=DataOnlineEntity2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DYNAMIC_DETAIL> DYNAMIC_DETAIL { get; set; }
        public DbSet<DYNAMIC_ITEM> DYNAMIC_ITEM { get; set; }
        public DbSet<DYNAMIC_VALID> DYNAMIC_VALID { get; set; }
        public DbSet<ERROR_CODE> ERROR_CODE { get; set; }
        public DbSet<ERROR_GROUP> ERROR_GROUP { get; set; }
        public DbSet<ERROR_GROUP_MAPPING> ERROR_GROUP_MAPPING { get; set; }
        public DbSet<FIELD_MESSAGE> FIELD_MESSAGE { get; set; }
        public DbSet<FUNCTION_INFO> FUNCTION_INFO { get; set; }
        public DbSet<OPERATION_INFO> OPERATION_INFO { get; set; }
        public DbSet<PRINT_MODULE_GROUP> PRINT_MODULE_GROUP { get; set; }
        public DbSet<PRINT_MODULE_GROUP_MEMBER> PRINT_MODULE_GROUP_MEMBER { get; set; }
        public DbSet<TBL_DISP_CONTENT> TBL_DISP_CONTENT { get; set; }
        public DbSet<TBL_EXCHANGE> TBL_EXCHANGE { get; set; }
        public DbSet<TBL_PRINT_MODULE> TBL_PRINT_MODULE { get; set; }
        public DbSet<TRANS_AUTO> TRANS_AUTO { get; set; }
        public DbSet<TRANS_COMMANDS> TRANS_COMMANDS { get; set; }
        public DbSet<TRANS_DEF> TRANS_DEF { get; set; }
        public DbSet<TRANS_SPLIT> TRANS_SPLIT { get; set; }
        public DbSet<VOID_CONFIG> VOID_CONFIG { get; set; }
    }
}
