//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYNAMIC_VALID
    {
        public decimal REC_NO { get; set; }
        public Nullable<decimal> MINLEN { get; set; }
        public Nullable<decimal> MAXLEN { get; set; }
        public Nullable<decimal> MINVAL { get; set; }
        public Nullable<decimal> MAXVAL { get; set; }
        public string INPUT_FLAG { get; set; }
        public string INPUT_TYPE { get; set; }
        public string RSV { get; set; }
        public string VERIFIED { get; set; }
        public string ADD_DATE { get; set; }
        public Nullable<decimal> OPTNUM1 { get; set; }
        public Nullable<decimal> OPTNUM2 { get; set; }
        public string OPTCODE { get; set; }
        public string INPUT_NAME { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
    }
}
