//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DYNAMIC_ITEM
    {
        public decimal RECNO { get; set; }
        public string TITLE { get; set; }
        public string DESCRIBE { get; set; }
        public Nullable<decimal> ITEM_NUM { get; set; }
        public string DATA_RULE { get; set; }
        public string VERIFIED { get; set; }
        public string MARKS { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public decimal DATA_SCR_TYPE { get; set; }
        public string VARIABLE { get; set; }
    }
}
