//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIELD_MESSAGE
    {
        public Nullable<long> TPOS_CODE { get; set; }
        public string FBSKD { get; set; }
        public string FIELD1 { get; set; }
        public string FIELD3 { get; set; }
        public string FIELD22 { get; set; }
        public string FIELD25 { get; set; }
        public string FIELD54 { get; set; }
        public string FIELD48_REQ { get; set; }
        public string FIELD48_RESP { get; set; }
        public Nullable<decimal> FLAG { get; set; }
        public string TRN_TYPE { get; set; }
        public string TRN_NAME { get; set; }
        public Nullable<decimal> MSG_TYPE { get; set; }
        public string MSG48_TYPE { get; set; }
        public Nullable<decimal> APP_ID { get; set; }
        public string RESV3 { get; set; }
        public string SUBFIELD { get; set; }
        public string FIELD4 { get; set; }
        public string FIELD60 { get; set; }
        public string VERIFIED { get; set; }
        public string DISPINFO { get; set; }
        public string ZFINFO { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public string FILL_FBSKD { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public decimal MSG_SPEC_VER { get; set; }
        public string FIELD48_REQ_PREFIX { get; set; }
        public string FIELD48_REQ_SUFFIX { get; set; }
        public string FIELD48_RESP_PREFIX { get; set; }
        public string FIELD48_RESP_SUFFIX { get; set; }
        public string FIELD63_REQ { get; set; }
        public string FIELD63_RESP { get; set; }
        public string FIELD57_REQ { get; set; }
        public string FIELD57_RESP { get; set; }
        public string FIELD62_REQ { get; set; }
        public string FIELD62_RESP { get; set; }
        public string FIELD2 { get; set; }
        public string REQ_MIN_BITMAP { get; set; }
        public string REQ_MAX_BITMAP { get; set; }
        public string RES_MIN_BITMAP { get; set; }
        public string RES_MAX_BITMAP { get; set; }
        public string BACK { get; set; }
        public string PRONAME { get; set; }
        public string PRODETAIL { get; set; }
        public string NEED_DIGITAL_SIGN { get; set; }
        public string TIDCNV_FLAG { get; set; }
        public Nullable<long> CNV_NO { get; set; }
    }
}
