//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCRIPT_FIELD
    {
        public decimal TRANS_TYPE { get; set; }
        public string FIELD3 { get; set; }
        public string FBSKD { get; set; }
        public string FIELD48_REQ { get; set; }
        public string FIELD48_RESP { get; set; }
        public string DELETE_FLAG { get; set; }
        public string MSG_TYPE { get; set; }
        public string FIELD48_TLV_REQ { get; set; }
        public string FIELD63_REQ { get; set; }
        public string FIELD63_RESP { get; set; }
    }
}
