//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebToolsBox.EntityFramework.DataLocalEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANS_DEF
    {
        public Nullable<decimal> TRANS_TYPE { get; set; }
        public string TRANS_CODE { get; set; }
        public string NEXT_TRANS_CODE { get; set; }
        public string AUTOVOID { get; set; }
        public string PIN_BLOCK { get; set; }
        public Nullable<decimal> FUNCTION_INDEX { get; set; }
        public string TRANS_NAME { get; set; }
        public Nullable<decimal> TELEPHONE_NO { get; set; }
        public string DISP_TYPE { get; set; }
        public string NII { get; set; }
        public string SERVER_CODE { get; set; }
        public string VERIFIED { get; set; }
        public string DEPTNO { get; set; }
        public decimal SYNC_STATUS { get; set; }
        public string DELETE_FLAG { get; set; }
        public System.DateTime CREATEDATE { get; set; }
        public string CREATER { get; set; }
        public System.DateTime LASTMODIFIED { get; set; }
        public string LASTMODIFIER { get; set; }
        public string REMARK { get; set; }
        public decimal CASHIERBILLAD_RECNO { get; set; }
    }
}
